"""Offline Vulkan/Metal shader generation. Requires SPIR-V-enabled DXC and SPIRV-Cross.

Validated tool versions: DXC v1.9.2607; SPIRV-Cross be71ee8c12cd7dc5ca8fa9581f708c2e8561fe2a.
No shader compiler is downloaded or invoked by the shipped game.
"""
import argparse
import hashlib
import pathlib
import re
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--spirv-cross')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
destination = root / 'src/render/shaders/generated'
destination.mkdir(exist_ok=True)
sources = ['effects_compute.hlsl', 'xbrz_compute.hlsli', 'xbrz_weights.hlsli', 'edge_corners.hlsli']
fingerprint = hashlib.sha256(b''.join((root / 'src/render/shaders' / name).read_bytes().replace(b'\r\n', b'\n')
                                     for name in sources)).hexdigest()
stamp = '// Source SHA-256: ' + fingerprint
if args.check:
    for xbrz in (0, 1):
        if stamp not in (destination / f'effects_portable_{xbrz}.hpp').read_text().splitlines()[:3]:
            raise SystemExit('Portable effects are stale; regenerate with DXC and SPIRV-Cross.')
    raise SystemExit(0)
if not args.dxc or not args.spirv_cross:
    parser.error('--dxc and --spirv-cross are required unless --check is specified')
for xbrz in (0, 1):
    with tempfile.TemporaryDirectory() as temp:
        spv = pathlib.Path(temp) / 'effects.spv'
        msl = pathlib.Path(temp) / 'effects.msl'
        subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0', '-T', 'cs_6_0', '-E', 'main',
                        '-D', f'STARFOX_ENABLE_XBRZ={xbrz}', '-D', 'STARFOX_SDL_GPU=1', '-Fo', str(spv),
                        str(root / 'src/render/shaders/effects_compute.hlsl')], check=True)
        subprocess.run([args.spirv_cross, str(spv), '--msl', '--msl-version', '20100', '--output', str(msl)], check=True)
        metal = msl.read_text()
        # SDL requires uniforms first, followed by read-only storage buffers.
        for name, slot in {'Settings': 0, 'layerTags': 1, 'indexedPixels': 2, 'surfaces': 3, 'shadowMask': 4}.items():
            metal, count = re.subn(r'(\b' + name + r'\s*\[\[buffer\()\d+(\)\]\])',
                                  lambda m: m[1] + str(slot) + m[2], metal)
            if count != 1:
                raise RuntimeError(f'Unexpected Metal binding for {name}: {count}')
        blob = spv.read_bytes()
        rows = [','.join(str(b) for b in blob[i:i+32]) for i in range(0, len(blob), 32)]
        text = '// Generated by tools/generate_portable_effects.py; do not edit.\n' + stamp + '\n#pragma once\n'
        text += 'namespace starfox::render::portable_shader {\ninline constexpr unsigned char spirv[]={\n'
        text += ',\n'.join(rows) + '\n};\ninline constexpr char metal[]=R"SFXMETAL(\n' + metal + ')SFXMETAL";\n}\n'
        (destination / f'effects_portable_{xbrz}.hpp').write_text(text, encoding='utf-8', newline='\n')
